# Generated by Django 2.0.7 on 2018-07-20 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('username', models.CharField(max_length=20, null=True, unique=True, verbose_name='账号')),
                ('password', models.CharField(max_length=20, null=True, verbose_name='密码')),
            ],
            options={
                'verbose_name_plural': '我的用户',
            },
        ),
    ]
