# Generated by Django 2.0.7 on 2018-07-20 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=12, null=True, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=12, null=True, unique=True, verbose_name='账号'),
        ),
        migrations.AddField(
            model_name='user',
            name='select',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo', verbose_name='选择'),
        ),
    ]
