# Generated by Django 2.0.7 on 2018-07-20 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180720_1345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name_plural': '用户详情'},
        ),
        migrations.AlterField(
            model_name='user',
            name='select',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo', verbose_name='选择'),
        ),
    ]
