# Generated by Django 2.0.5 on 2018-07-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180715_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(db_column='FId', primary_key=True, serialize=False),
        ),
    ]
