# Generated by Django 2.0.5 on 2018-07-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180715_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.IntegerField(db_column='FId', default=1, primary_key=True, serialize=False),
        ),
    ]
