# Generated by Django 2.0.7 on 2018-07-20 09:24

from django.db import migrations
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180720_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='list',
            field=user.models.ListField(null=True, verbose_name='选择'),
        ),
    ]
