# Generated by Django 2.0.6 on 2018-07-17 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20180717_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time',
            field=models.DateTimeField(null=True, verbose_name='时间'),
        ),
    ]
