# Generated by Django 2.0.6 on 2018-07-17 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='time',
        ),
    ]
