# Generated by Django 2.0.5 on 2018-07-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_user_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time',
            field=models.DateTimeField(null=True, verbose_name='时间'),
        ),
    ]
