# Generated by Django 2.0.6 on 2018-07-19 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_user_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time',
            field=models.DateField(null=True, verbose_name='我的时间'),
        ),
    ]
