# Generated by Django 2.0.6 on 2018-07-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_user_shirt_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='shirt_size',
        ),
        migrations.AlterField(
            model_name='user',
            name='time',
            field=models.DateField(blank=True, null=True, verbose_name='我的时间'),
        ),
    ]
