# Generated by Django 2.0.6 on 2018-07-19 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_user_shirt_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='shirt_size',
        ),
    ]
