# Generated by Django 2.0.6 on 2018-07-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_remove_user_shirt_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1, verbose_name='尺寸'),
        ),
    ]
