# Generated by Django 2.0.6 on 2018-07-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_user_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='size',
            field=models.CharField(blank=True, choices=[('A', '小a'), ('B', '小b'), ('C', '小c')], max_length=1, verbose_name='尺寸'),
        ),
    ]
