# Generated by Django 2.0.6 on 2018-07-19 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20180719_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='age',
            field=models.TimeField(null=True, verbose_name='我的世界'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=5, null=True, verbose_name='我的名字'),
        ),
        migrations.AlterField(
            model_name='user',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Manufacturer', verbose_name='我的'),
        ),
    ]
