# Generated by Django 2.0.6 on 2018-07-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20180719_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '我的用户啊'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='manufacturer',
        ),
        migrations.AddField(
            model_name='user',
            name='manufacturer',
            field=models.ManyToManyField(blank=True, null=True, to='user.Manufacturer', verbose_name='我的'),
        ),
    ]
