# Generated by Django 2.0.6 on 2018-07-19 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0019_auto_20180719_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='manufacturer',
        ),
        migrations.AddField(
            model_name='user',
            name='usera',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
