# Generated by Django 2.0.6 on 2018-07-19 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20180719_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='usera',
        ),
        migrations.AddField(
            model_name='user',
            name='ff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Manufacturer', verbose_name='尺寸'),
        ),
    ]
