# Generated by Django 2.0.6 on 2018-07-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20180719_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ff',
        ),
        migrations.AddField(
            model_name='user',
            name='members',
            field=models.ManyToManyField(to='user.Manufacturer'),
        ),
    ]
