# Generated by Django 2.0.6 on 2018-07-19 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_auto_20180719_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='bb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='members',
            field=models.ManyToManyField(through='user.Manufacturer', to='user.Person'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='qq',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Person'),
        ),
    ]
